### PR TITLE
Filter directory contents before applying pull to repos

### LINKED ISSUE #58: The new `gh classroom pull` command fails if any other files are in target directory
This may be similar to issue #14 but I have put test files that I use to test student submissions locally in the "submissions-x" folder, and just noticed that the `pull` command fails at this point (I have aliased the full `gh classroom pull student-repos` with my own `pull` script):

```
PS C:\Users\physcrowley\Documents\ics4u\23-01> pull
? Select a classroom: ICS4U-Crowley-2023-24
? Select an assignment: encapsulated
Pulling repo: C:\Users\physcrowley\Documents\ics4u\23-01\encapsulated-submissions\TeacherTest.java
2023/11/05 15:18:49 chdir C:\Users\physcrowley\Documents\ics4u\23-01\encapsulated-submissions\TeacherTest.java: The directory name is invalid.
PS C:\Users\physcrowley\Documents\ics4u\23-01\encapsulated-submissions> ls

    Directory: C:\Users\physcrowley\Documents\ics4u\23-01\encapsulated-submissions

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2023-11-02   1:20 PM                encapsulated-redacted
d-----        2023-11-02   1:21 PM                encapsulated-redacted
d-----        2023-11-02   1:21 PM                encapsulated-redacted
d-----        2023-11-02   1:21 PM                encapsulated-redacted
d-----        2023-11-02   1:22 PM                encapsulated-redacted
d-----        2023-11-02   1:22 PM                encapsulated-redacted
d-----        2023-11-02   1:22 PM                encapsulated-redacted
d-----        2023-11-02   1:22 PM                encapsulated-redacted
-a----        2023-11-02  11:17 AM            361 build.xml
-a----        2023-11-02   1:25 PM            442 runAllTests.ps1
-a----        2023-11-02   1:16 PM            110 TeacherTest.java
```

>@shanep - love the new `pull` feature, btw, and have stopped maintenance on my own set of tools in favor of this one.

### PR DESCRIPTION
**Pull request by physcrowley**
### What are you trying to accomplish?

I added a filter for the `pull` command that only looks for local directories in the "x-submissions" folder before running the pulls on each student repo.

This allows companion files to be added to the "x-submissions" folder, such as comment files or tests, that the teacher may use on the student-repos.

fixes #58

### What approach did you choose and why?

I traversed the originally extracted entries and simply applied `isDir()` to add only directories to the list of entries that continue on in the tool's existing code.

I added this change because it offers flexibility to the teacher. It also makes sure that the pull command is only attempting its operations on entries that are directories.

### What should reviewers focus on?

I have run tests on "dirty" parent directories that otherwise fail with the current tool. They work as expected: ignoring files and pulling the repos. It would be important to run further tests on the code validity.

I have limited knowledge and experience with the Go language, so it would be important for someone with experience to make sure that I haven't introduced unintended side effects.

### CODE REVIEW

**Comment by physcrowley** [comment]
My implementation traverses all the items in the repo and creates a new list to pass on to the existing code, but it may be more efficient to filter the list while it's being created initially. I have small classes (high school), so I don't see any lag, but a larger classroom (university, MOOC) might.

**Review by octosteve — APPROVED** [review]

File: cmd/gh-classroom/pull/student-repos/student-repos.go [hunk 1]
```diff
@@ -71,11 +71,19 @@ func NewCmdStudentReposPull(f *cmdutil.Factory) *cobra.Command {
...
+			//filter entries to only directories
+			var entries []os.DirEntry
+			for _, r := range all_entries {
+				if r.IsDir() {
+					entries = append(entries, r)
+				}
+			}
+
 			for _, r := range entries {
 				clonePath := filepath.Join(fullPath, r.Name())
```
Comment (octosteve) [inline cmd/gh-classroom/pull/student-repos/student-repos.go:88]: Would it make sense to add a conditional here instead of filtering the list? That way we only have to loop the one time.

**Review by octosteve — CHANGES_REQUESTED** [review]

File: cmd/gh-classroom/pull/student-repos/student-repos.go (hunk 1 above)
Comment (physcrowley) [reply cmd/gh-classroom/pull/student-repos/student-repos.go:88]: That's a good idea. Like at line 88 adding a guard clause. I'll try it out.

**Review by zrdaley — APPROVED** [review]
Thank you for this submission!

**Review by octosteve — APPROVED** [review]

**Comment by physcrowley** [comment]
Can this PR be closed now? I'm a first timer outside of student code, so I apologise if this is an obvious question.

**Comment by zrdaley** [comment]
@physcrowley yes, once approved PRs can be merged 😄 then we create a new release and users can upgrade their CLI version
